services:
  postgres:
    image: postgres:15
    container_name: rumon-postgres-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rumon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    networks:
      - rumon-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rumon-api-local
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=rumon
      - NODE_ENV=development
      - JWT_SECRET=desenvolvimento_jwt_secret_local
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rumon-network

volumes:
  postgres_local_data:

networks:
  rumon-network:
    driver: bridge 