version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: rumon-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rumon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rumon-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rumon-api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=rumon
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - rumon-network

volumes:
  postgres_data:

networks:
  rumon-network:
    driver: bridge 