services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: rumon-mysql
  #   ports:
  #     - "6033:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - rumon-network
  #   healthcheck:
  #       test: ["CMD", "curl", "-f", "http://localhost:3306"]
  #       interval: 10s
  #       timeout: 3s
  #       retries: 15
  postgres:
    image: postgres:15
    container_name: rumon-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE:-rumon}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rumon-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rumon-api
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_DATABASE=${DB_DATABASE:-rumon}
      - NODE_ENV=${NODE_ENV:-development}
      - JWT_SECRET=${JWT_SECRET}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rumon-network

# volumes:
#   mysql_data:

volumes:
  postgres_data:

networks:
  rumon-network:
    driver: bridge 